use gutencore::GutenCore;
use std::path::Path;

fn main() -> anyhow::Result<()> {
    let project_path = Path::new("guardian_test");
    
    // 1. Create a new project
    println!("--- 1. Creating Guardian Project ---");
    let mut core = GutenCore::new_project(project_path, "The Guardian Engine", "en")?;
    
    // 2. Add resource via orchestrated API
    println!("\n--- 2. Adding Image resource ---");
    core.add_resource(
        "logo".to_string(), 
        b"dummy_image_data", 
        "image/png", 
        "Images/logo.png"
    )?;
    println!("  ✔ Logo added to disk and manifest");
    
    // 3. Path Resolution
    println!("\n--- 3. Path Resolution ---");
    let rel = core.get_relative_path("chap1", "logo")?;
    println!("  Relative link from Chapter 1 to Logo: {}", rel);
    assert_eq!(rel, "../Images/logo.png");
    
    // 4. Content Guardian (Saving dirty HTML)
    println!("\n--- 4. Content Guardian (XHTML Enforcement) ---");
    let dirty_html = r#"<h1>Chapter 1</h1><h2>Section 1.1</h2><p>This is a test with a <br> unclosed tag and an <b>unclosed bold tag. <img src="../Images/logo.png">"#;
    println!("  Saving dirty HTML...");
    core.save_chapter("chap1", dirty_html)?;
    
    let saved_content = std::fs::read_to_string(core.get_resource_path("chap1")?)?;
    println!("  Saved (Sanitized) Content:\n---");
    println!("{}", saved_content);
    println!("---");
    assert!(saved_content.contains("xmlns=\"http://www.w3.org/1999/xhtml\""));
    assert!(saved_content.contains("lang="));
    assert!(saved_content.contains("<link rel=\"stylesheet\""));
    println!("  ✔ Content is now valid XHTML with lang and CSS links");

    // 5. Reactive NAV Sync
    println!("\n--- 5. Reactive NAV Sync ---");
    println!("  Updating metadata title...");
    core.set_metadata(Some("GutenAIR: The Guardian".to_string()), None, None);
    println!("  Saving project (triggers nav update)...");
    core.save()?;
    
    let nav_content = std::fs::read_to_string(core.get_resource_path("nav")?)?;
    println!("  Autogenerated NAV Content (Partial):\n---");
    println!("{}", nav_content);
    println!("---");
    assert!(nav_content.contains("GutenAIR: The Guardian"));
    println!("  ✔ NAV synchronized automatically");

    // 6. Project Portability (Config)
    println!("\n--- 6. Project Portability (gutenAIR.config) ---");
    println!("  Checking for config file...");
    let config_path = project_path.join("META-INF/gutenAIR.config");
    assert!(config_path.exists());
    let config_json = std::fs::read_to_string(&config_path)?;
    println!("  Config Content:\n{}", config_json);

    println!("\n  Modifying config and editor state...");
    core.config.editor_state.insert("last_sync".to_string(), "2026-04-16".to_string());
    core.config.editor_state.insert("ai_prompt".to_string(), "Write a mystery novel".to_string());
    
    // Test custom CSS order using high-level methods
    println!("  Adding extra CSS and changing injection order...");
    core.add_style("extra_css", ".extra { color: red; }")?;
    core.set_style_as_default("extra_css")?;
    core.save()?;

    let chap1_content = std::fs::read_to_string(core.get_resource_path("chap1")?)?;
    let chap1_after = core.sanitize_to_xhtml("chap1", &chap1_content)?;
    println!("  Sanitized Chap1 with custom CSS order:\n---");
    println!("{}", chap1_after);
    println!("---");
    assert!(chap1_after.contains("style.css\"/>\n  <link rel=\"stylesheet\" type=\"text/css\" href=\"../Styles/extra_css.css\"/>"));
    assert!(std::fs::read_to_string(&config_path)?.contains("Write a mystery novel"));
    println!("  ✔ Configuration and CSS order verified");

    // 7. Deep Validation (Orphans)
    println!("\n--- 7. Deep Validation ---");
    std::fs::write(project_path.join("OEBPS/orphan.txt"), "I am not in the manifest")?;
    let (errors, orphans) = core.validate_integrity_deep();
    println!("  Integrity errors: {}", errors.len());
    println!("  Orphaned files found: {}", orphans.len());
    for orphan in orphans {
        println!("  - Orphan: {:?}", orphan.file_name().unwrap());
    }
    assert_eq!(core.validate_integrity_deep().1.len(), 1);
    
    println!("\n--- GUARDIAN VERIFIED ---");
    Ok(())
}
